//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataEF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BeaujeauxEntities : DbContext
    {
        public BeaujeauxEntities()
            : base("name=BeaujeauxEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__RefactorLog> C__RefactorLog { get; set; }
        public virtual DbSet<Goalie> Goalies { get; set; }
        public virtual DbSet<GoalieSeasonStat> GoalieSeasonStats { get; set; }
        public virtual DbSet<League> Leagues { get; set; }
        public virtual DbSet<Season> Seasons { get; set; }
        public virtual DbSet<SeasonType> SeasonTypes { get; set; }
        public virtual DbSet<Skater> Skaters { get; set; }
        public virtual DbSet<Team> Teams { get; set; }
        public virtual DbSet<Franchise> Franchises { get; set; }
        public virtual DbSet<RequestSubmission> RequestSubmissions { get; set; }
        public virtual DbSet<RequestType> RequestTypes { get; set; }
        public virtual DbSet<SkaterSeasonStat> SkaterSeasonStats { get; set; }
    }
}
