//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class RequestSubmission
    {
        public int Id { get; set; }
        public int RequestTypeId { get; set; }
        public System.DateTime DateSubmitted { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> DateComplete { get; set; }
        public string CompleteComment { get; set; }
    
        public virtual RequestType RequestType { get; set; }
    }
}
