//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Season
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Season()
        {
            this.GoalieSeasonStats = new HashSet<GoalieSeasonStat>();
            this.Teams = new HashSet<Team>();
            this.SkaterSeasonStats = new HashSet<SkaterSeasonStat>();
        }
    
        public int Id { get; set; }
        public int Number { get; set; }
        public int SeasonTypeId { get; set; }
        public int LeagueId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GoalieSeasonStat> GoalieSeasonStats { get; set; }
        public virtual League League { get; set; }
        public virtual SeasonType SeasonType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Team> Teams { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SkaterSeasonStat> SkaterSeasonStats { get; set; }
    }
}
