CREATE TABLE [dbo].[GoalieSeasonStats]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY, 
    [GoalieId] INT NOT NULL, 
    [TeamId] INT NOT NULL,
    [SeasonId] INT NOT NULL,
    [IsSubtotal] BIT NOT NULL,
    [GP] INT NOT NULL, 
	[W] INT NOT NULL, 
	[L] INT NOT NULL, 
	[OTL] INT NOT NULL, 
	[MP] INT NOT NULL, 
	[PIM] INT NOT NULL, 
	[SO] INT NOT NULL, 
	[GA] INT NOT NULL, 
	[SA] INT NOT NULL, 
	[SAR] INT NOT NULL, 
	[A] INT NOT NULL, 
	[EG] INT NOT NULL, 
	[PSS] INT NOT NULL, 
	[PSA] INT NOT NULL, 
	[ST] INT NOT NULL, 
	[BG] INT NOT NULL, 
	[S1] INT NOT NULL, 
	[S2] INT NOT NULL, 
	[S3] INT NOT NULL, 
    CONSTRAINT [FK_GoalieSeasonStats_ToGoalie] FOREIGN KEY ([GoalieId]) REFERENCES [Goalie]([Id]), 
    CONSTRAINT [FK_GoalieSeasonStats_ToSeason] FOREIGN KEY ([SeasonId]) REFERENCES [Season]([Id]), 
    CONSTRAINT [FK_GoalieSeasonStats_ToTeam] FOREIGN KEY ([TeamId]) REFERENCES [Team]([Id]), 
)
